# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='investor',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='fertility_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='share_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='share_quantity',
            field=models.IntegerField(),
        ),
    ]
