# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_auto_20171115_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='gender',
        ),
        migrations.AddField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
