# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20171115_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='username',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
