# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
