# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20171119_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='gender',
        ),
    ]
