# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_land_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Farmer'),
        ),
    ]
