# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20171120_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
