# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_branch_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Branch'),
        ),
    ]
