# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_revenue_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='total_revenue',
        ),
    ]
