# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_revenue_total_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='land',
        ),
    ]
