# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20171126_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Farmer'), (2, 'Investor'), (3, 'Employee')], default=2),
        ),
    ]
