# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_land_total_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='share_sold',
            field=models.IntegerField(default=0),
        ),
    ]
