# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_share_share_amount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='share_amount_percentage',
        ),
    ]
