# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_remove_share_share_amount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
