# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_share_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
