# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_auto_20171215_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
