# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_auto_20171215_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='budget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.Land'),
        ),
    ]
