# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_auto_20171215_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='budget',
            new_name='land_revenue',
        ),
    ]
