# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('age', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('age', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('share_price', models.IntegerField(max_length=20)),
                ('share_quantity', models.IntegerField(max_length=20)),
                ('fertility_rate', models.IntegerField(max_length=20)),
            ],
        ),
    ]
