# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20171115_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=250)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(max_length=200, upload_to='')),
                ('NID', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('bank_credentials', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='gender',
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('username', 'password')]),
        ),
    ]
