# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20171115_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mobile_no',
            field=models.CharField(default=123456, max_length=250),
            preserve_default=False,
        ),
    ]
