# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrifin', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('number_of_employee', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
    ]
