# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrifin', '0003_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fartility_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('location', models.CharField(max_length=500)),
                ('share_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('share_quantity', models.DecimalField(decimal_places=0, max_digits=5)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrifin.Branch')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrifin.Farmer')),
            ],
        ),
    ]
