# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrifin', '0005_auto_20171113_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='full_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
