# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrifin', '0008_crop_fertilizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('irrigation_fees', models.DecimalField(decimal_places=2, max_digits=20)),
                ('other_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrifin.Crop')),
                ('land_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrifin.Land')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('land_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrifin.Land')),
            ],
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='crop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrifin.Crop'),
        ),
    ]
