# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Farmer'), (2, 'Investor'), (3, 'Employee')], default=1),
        ),
    ]
